<?php

declare(strict_types=1);

namespace NeneServe\Tests\Support;

use NeneServe\Support\MysqlToPgsqlTranslator;
use PHPUnit\Framework\TestCase;

final class MysqlToPgsqlTranslatorTest extends TestCase
{
    public function testTranslatesCreateTableConstructs(): void
    {
        $mysql = <<<'SQL'
            CREATE TABLE users (
                id              CHAR(36)     NOT NULL,
                role            ENUM('superadmin', 'editor') NOT NULL,
                measurement     TINYINT(1)   NOT NULL DEFAULT 1,
                created_at      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                PRIMARY KEY (id),
                UNIQUE KEY uq_users_org_email (organization_id, email),
                KEY idx_users_org (organization_id)
            ) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
            SQL;

        $pg = (new MysqlToPgsqlTranslator())->translateFile($mysql);

        // Type rewrites (original column alignment is preserved, so match tokens).
        self::assertStringContainsString('VARCHAR(36)', $pg);
        self::assertStringContainsString('SMALLINT', $pg);
        self::assertStringContainsString('TIMESTAMP', $pg);
        self::assertStringContainsString('DEFAULT CURRENT_TIMESTAMP', $pg);
        self::assertStringContainsString('TEXT NOT NULL', $pg);
        // ON UPDATE is dropped; ENGINE tail stripped.
        self::assertStringNotContainsString('ON UPDATE', $pg);
        self::assertStringNotContainsString('ENGINE', $pg);
        self::assertStringNotContainsString('ENUM', $pg);
        // Unique key becomes an inline constraint; non-unique key a separate index.
        self::assertStringContainsString('CONSTRAINT uq_users_org_email UNIQUE (organization_id, email)', $pg);
        self::assertStringContainsString('CREATE INDEX idx_users_org ON users (organization_id);', $pg);
        self::assertStringNotContainsString('KEY idx_users_org', $pg);
    }

    public function testTranslatesAlterTableConstructs(): void
    {
        $mysql = <<<'SQL'
            ALTER TABLE audit_events
                ADD COLUMN seq BIGINT NOT NULL AUTO_INCREMENT UNIQUE FIRST,
                ADD COLUMN hash CHAR(64) NOT NULL DEFAULT '' AFTER occurred_at,
                ADD KEY idx_audit_seq (seq);
            SQL;

        $pg = (new MysqlToPgsqlTranslator())->translateFile($mysql);

        self::assertStringContainsString('GENERATED BY DEFAULT AS IDENTITY', $pg);
        self::assertStringNotContainsString('AUTO_INCREMENT', $pg);
        self::assertStringNotContainsString('FIRST', $pg);
        self::assertStringNotContainsString('AFTER occurred_at', $pg);
        self::assertStringContainsString('hash VARCHAR(64) NOT NULL', $pg);
        self::assertStringContainsString('CREATE INDEX idx_audit_seq ON audit_events (seq);', $pg);
    }

    public function testDropForeignKeyBecomesDropConstraint(): void
    {
        $pg = (new MysqlToPgsqlTranslator())->translateFile('ALTER TABLE users DROP FOREIGN KEY fk_users_org;');

        self::assertStringContainsString('ALTER TABLE users DROP CONSTRAINT fk_users_org;', $pg);
    }
}
